#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep 18 11:31:25 2019

@author: JeffHalley
"""

from pyspark import SparkContext

from pyspark.sql import HiveContext, SQLContext, Row
from pyspark.sql.types import *
from datetime import datetime
from pyspark.sql.functions import col, date_sub, log, mean, to_date, udf, unix_timestamp
from pyspark.sql.window import Window
from pyspark.sql import DataFrame

sc =SparkContext()
sc.setLogLevel("DEBUG")
sqlContext = SQLContext(sc)

indata_creds = sqlContext.read.text('s3a://jeff-halley-s3/split_reddit_comments_2018_07/subreddit_topics.csv')

(, 'RdpufBNoAKjExLcEmhQGKUsJ0Fq5UOT68p+SuNDY')



from pyspark.sql import DataFrameWriter
import sys
from pyspark import SparkContext, SparkConf
from pyspark.sql import SparkSession
          
spark = SparkSession.builder.appName("test").getOrCreate()
        
reddit_df = spark.read.csv("s3a://jeff-halley-s3/split_reddit_comments_2018_07/xaa") 
#reddit_df = spark.read.csv("subreddit_topics.csv")

reddit_df.count()

pyspark  --master spark://10.0.0.24:7077 --packages org.apache.hadoop:hadoop-aws:2.7.3
