"""empty message

Revision ID: ba7f75a045a7
Revises: 86e4819ec3b0
Create Date: 2019-09-21 18:49:25.512260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba7f75a045a7'
down_revision = '86e4819ec3b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('word', sa.String(), nullable=True),
    sa.Column('count', sa.BigInteger(), nullable=True),
    sa.Column('count_per_day_all', sa.BigInteger(), nullable=True),
    sa.Column('total_word_count_per_day_all', sa.BigInteger(), nullable=True),
    sa.Column('total_word_count_per_day_topic', sa.BigInteger(), nullable=True),
    sa.Column('sub_freq_to_all_freq_ratio', sa.Float(), nullable=True),
    sa.Column('change_in_rolling_average', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('word')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('word', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('count', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('count_per_day_all', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_word_count_per_day_all', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_word_count_per_day_topic', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sub_freq_to_all_freq_ratio', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('change_in_rolling_average', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='word_pkey')
    )
    op.drop_table('reddit_results')
    # ### end Alembic commands ###
